# server part of the live-nano-type app
# logic - the file test.tsv (generated by jsa) is read periodically
# and the results are plotted as bubble and table


function(input, output, session) {
  
  logfilename <- "test.tsv"
  
  options(shiny.launch.browser = TRUE)

  # session$onSessionEnded(function() {
  #   unlink("test.tsv")
  # })
  
  
  fileData <- reactiveFileReader(500, session, logfilename, fread)
 
  
  # reactive vals for storing total and mapped reads
  readsData <- reactiveValues(mapped = 0, total = 0)
  
  filteredData <- reactive({
    
    validate(need(
      file.exists(logfilename), "error"
    ))
    
    readsData$mapped <- fileData()[1,8] %>% as.numeric()
    readsData$total <- fileData()[1,3] %>% as.numeric()
    
    fileData() %>% 
      mutate(Abundance_t = sAligned/readsData$total, Abundance_m = sAligned/readsData$mapped) %>%
      filter(prob > input$probfilter & Abundance_m > (input$abundfilter/100))
  })
  
  
  
  output$rawtable <- renderTable({
    filteredData()
  })
  
  output$mreads <- renderValueBox({
    
    valueBox(
      value = readsData$mapped,
      subtitle = "Mapped reads",
      icon = icon("dna")
    )
  })
  output$treads <- renderValueBox({
    valueBox(
      value = readsData$total,
      subtitle = "Total reads",
      icon = icon("dna")
    )
  })
  
  output$abundanceTable <- renderFormattable({
    if (nrow(filteredData()) == 0)
      return()
    
    df <- filteredData() %>%
      filter(step == max(step)) %>%
      select(species, prob, sAligned, Abundance_m) %>%
      mutate(Abundance_m = formattable::percent(Abundance_m)) %>%
      arrange(desc(sAligned)) %>%
      mutate(prob = round(prob, 2)) %>%
      # just the top 20?
      head(20)
    
    formattable(df, list(sAligned = formattable::color_bar("lightgreen"),
                         Abundance_m = formattable::color_bar("lightgreen"),
                         prob = formattable::color_bar("lightgreen")))
    
  })
  
  output$abundancePlot <- renderBubbles({
    if (nrow(filteredData()) == 0)
      return()
    df <- filteredData() %>%
      filter(step == max(step)) %>%
      arrange(desc(Abundance_m)) %>%
      # assign colors according to prob
      mutate(prob_color = scales::col_numeric("YlGn", domain = c(0,1))(prob)) %>%
     # just the top 20?
      head(20)
    
    bubbles(value = df$sAligned, 
            label = df$species, 
            key = df$species, 
            color = df$prob_color,
            tooltip = paste("Prob = ", df$prob, "\n", "Reads = ", df$sAligned))
    
  })
  
  
}